<?php
define('IDS_NUM_COMMENTS1', 'No comments');
define('IDS_NUM_COMMENTS2', '%d comments');
define('IDS_POSTED_BY', 'Posted by %name &nbsp; &#149; &nbsp; %time');
define('IDS_POSTED_TIME', 'l, Y-F-d');
define('IDS_COMMENT_BY', '%name wrote on %time:');
define('IDS_COMMENT_TIME', 'Y-F-d H:i:s');
define('IDS_AUTH_REMEMBER', 'Remember me');
define('IDS_AUTH_EMAIL', 'Your email');
define('IDS_AUTH_PASSWORD', 'Your password');
define('IDS_AUTH_WELCOME1', 'Welcome, %name (<a href=%logout>Log out</a> | <a href=%post>Post</a> | <a href=%account>My account</a>)');
define('IDS_AUTH_WELCOME2', 'Welcome, anonymous (<a href=%link>Log in</a>)');
define('IDS_LOGGED_IN', 'Already logged in');
define('IDS_MUST_LOGIN', 'You must login in order to post messages');
define('IDS_EMPTY_HEADER', 'The title of a message may not be empty');
define('IDS_EMPTY_BODY', 'The body of a message may not be empty');
define('IDS_UNKNOWN_USER', 'Unknown user');
define('IDS_NO_USER_INFO', '<i>User information is anavailable</i>');
define('IDS_AUTH_ERROR', 'Authentication error');
define('IDS_USER_POSTS', 'Posts, made by %s');
define('IDS_NEW_POST_OK', 'Your posting is successfully saved. <a href=%s>Click here</a> to read it.');
define('IDS_POST_OK', 'Your comment is successfully saved');
define('IDS_NEXT_PAGE', 'Next page');
define('IDS_PREV_PAGE', 'Previous page');
define('IDS_PAGES1', 'Pages: ');
define('IDS_PAGES2', '');
define('IDS_BAD_EMAIL', 'Email address is not valid');
define('IDS_EMAIL_EXISTS', 'The email already exists in database. Please use password reminder form below in order to get your password.');
define('IDS_REGISTRATION_OK', 'Registration information successfully sent to you.');
define('IDS_SENDMAIL_ERROR', 'Error sending email.');
define('IDS_SENDMAIL_OK', 'Email successfully sent.');
define('IDS_DEFAULT_NAME', 'Subscriber');
define('IDS_EMAIL_NOT_FOUND', 'The email address is not found in the database');
define('IDS_ALL_REQ', 'All fields are required!');
define('IDS_PASSW_NOT_MATCH', 'New passwords do not match');
define('IDS_USER_NOT_FOUND', 'Specified email and password is not found in the database');
define('IDS_PASSWORD_CHANGED', 'Password successfully updated');
define('IDS_URL_POSTING_DENIED', '#');
define('IDS_POSTING_DENIED', 'You may not post new messages.');
define('IDS_INFO_SAVED', 'Your information is updated');
define('IDS_ADMIN_EDIT', 'Edit message');
define('IDS_ADMIN_DELETE', 'Delete message');
define('IDS_ADMIN_BAN', 'Ban user');
define('IDS_MONTHS', 'January February March April May June July August September October November December');
define('IDS_DAYSOFWEEK', 'SU MO TU WE TR FR SA');
define('IDS_LOW_RIGHTS', 'You do not have enought rights for this action');
define('IDS_BAN_USER_CONFIRM', 'Are you sure you want to ban the user and delete all his messages and comments?\n\nThere will be no undo for this action!');
define('IDS_DEL_COM_CONFIRM', 'Are you sure you want to delete the comment?\n\nThere will be no undo for this action!');
define('IDS_DEL_MSG_CONFIRM', 'Are you sure you want to delete the message and ALL comments?\n\nThere will be no undo for this action!');
define('IDS_DELETE_OTHER', 'You may not delete messages of other users.');
define('IDS_DELETE_OK', 'The message successfully erased');
define('IDS_DELETE_ERROR', 'The message does not exist!');
define('IDS_MSG_NOT_EXISTS', 'Topic does not exist!');
define('IDS_BAN_YOURSELF', 'You can not ban yourself');
define('IDS_USER_BAN_OK', 'User successfully banned.<br>All his messages are removed from database.');
define('IDS_RSS_COMMENTS', 'Subscribe to comments to this posting');
define('IDS_RSS_USER', 'Subscribe to postings of the user');
define('IDS_TAG1', 'HTML tag problem at the begining of text (">" is unexpected)');
define('IDS_TAG2', 'HTML tag not closed at the end of a text (">" is expected, but not found)');
define('IDS_TAG3', 'HTML tag not closed ("<TAG" without corresponding ">" character)');
define('IDS_TAG4', '">" is unsexpected');
define('IDS_TAG5', 'Closed tag "</%s>" found without corresponding opened one');
define('IDS_TAG6', 'Tag "<%s>" is not allowed!');
define('IDS_READ_MORE', 'read more');
?>
